---
title: "04 Iverse probability weighting"
author: "Yuze Zheng"
date: "2026-02-20"
update_date: !r paste("Updated on:", format(Sys.time(), '%d %B, %Y'))
output: html_document
---
```{r setup}
library(fastglm)
library(data.table)
library(ggplot2)
library(dplyr)
```

```{r}
load('dt+res_trad.RData')
keep <- c('dt','res_trad')
rm(list = setdiff(ls(), keep))
```

#PP
# Step1: data cleaning remove all the trtment after intional treatment 
```{r}
dt_cleaned <- dt[, trt_time := which(trt == 1)[1], by = id]
dt_cleaned <- dt_cleaned[cal_time <= trt_time -1 | is.na(trt_time) == T]
```

```{r,fig.height=5,fig.width=6}
# this is san check for how many new initation in the world 
dt_cleaned %>% select(trt, cal_time)%>% group_by(cal_time)%>% summarise(per_A = sum(trt)/100000) %>% 
  plot(main = "Proportion of \n Treatment Initiation Overtime ",
       sub = 'under assumption n = 100,000',
       ylab =" Percentage of Initiation (%)",
       xlab = "Time after eligible (Month)", ylim = c(0,1))
```
```{r}
cat("the precent of treated individual in this dataset is",sum(dt_cleaned$trt)/nrow(dt_cleaned)*100, "%")
```
# Step 2: estimate population trt 
```{r}
mat_boot_numA <- model.matrix(~ cal_time + cal_timesqr, dt_cleaned)
A <- dt_cleaned$trt
numprobA <- fastglm(x = mat_boot_numA,
                    y = A,
                    family = binomial(link = "logit"))
```

#Step 3: estimate A by individual 
```{r}
mat_boot_denomA <- model.matrix( ~ L + cal_time + cal_timesqr, dt_cleaned)
denomprobA <- fastglm(x = mat_boot_denomA,
                        y = A,
                        family = binomial(link = "logit"))
```


#Step4: weight estimation
```{r}
dt_cleaned$ipw.num <- predict(numprobA, mat_boot_numA, type = "response")
dt_cleaned$ipw.denom <- predict(denomprobA, mat_boot_denomA, type = "response")
dt_cleaned$wt <- ifelse(dt_cleaned$trt == 1,
                        dt_cleaned$ipw.num / dt_cleaned$ipw.denom,
                        (1 - dt_cleaned$ipw.num) / (1 - dt_cleaned$ipw.denom))
```

#Step5: cleaning remove date 
```{r}
dt_ipw_pp<- dt_cleaned %>% filter(cal_time >0 & trt == 0)
```

##ITT 
#filter for only initators
```{r}
dt_cleaned <- dt%>% filter(cal_time == 0)
```
#building model matrix 
```{r}
mat_boot_numA <- model.matrix(~ 1, dt_cleaned)
A <- dt_cleaned$trt
numprobA <- fastglm(x = mat_boot_numA,
                    y = A,
                    family = binomial(link = "logit"))

mat_boot_denomA <- model.matrix( ~ L , dt_cleaned)
denomprobA <- fastglm(x = mat_boot_denomA,
                        y = A,
                        family = binomial(link = "logit"))
```

#weight estimation
```{r}
dt_cleaned$ipw.num <- predict(numprobA, mat_boot_numA, type = "response")
dt_cleaned$ipw.denom <- predict(denomprobA, mat_boot_denomA, type = "response")
dt_cleaned$wt <- ifelse(dt_cleaned$trt == 1,
                        dt_cleaned$ipw.num / dt_cleaned$ipw.denom,
                        (1 - dt_cleaned$ipw.num) / (1 - dt_cleaned$ipw.denom))
```

#data merge
```{r}
dt_cleaned<- dt_cleaned %>% select(id,wt)
df_ipw_itt <- merge(dt,dt_cleaned,by= "id")
```

