---
title: "data_simulation"
author: "Yuze Zheng"
date: "2026-02-12"
output: html_document
---

```{r setup, include=FALSE}
library("readxl")
library("stringr")
library("flextable")
library("officer")
library("dplyr")
library("tidyr")
library("ggtext")
library("fastglm")
library("data.table")
library(ggplot2)
```

## Param
@param K max number of time points
@param nsim number of simulated datasets
@param A vector of treatment parameters
@param seed Random seed

```{r param}
seed <- .Random.seed
nsim = 100000
K = 60

A <- c(beta_0_A = -1.5,
       beta_U1_A = 0,
       beta_t_A = -4.8,
       beta_t2_A =0)

Y <- c(beta_0_Y = -6,
       beta_t_Y = 0.01 ,
       beta_t2_Y = 0,
       beta_A_Y = 0,
       beta_tA_Y = 0,
       beta_t2A_Y= 0)
```

```{r}
# Handle vector vs individual parameter inputs
  if (!is.null(A)) {
    stopifnot(length(A) == 4)
    beta_0_A <- A[1]
    beta_U1_A <- A[2]
    beta_t_A <- A[3]
    beta_t2_A <- A[4]
  }
  
  if (!is.null(Y)) {
    stopifnot(length(Y) == 6)
    beta_0_Y <- Y[1]
    beta_t_Y <- Y[2]
    beta_t2_Y <- Y[3]
    beta_A_Y <- Y[4]
    beta_tA_Y <- Y[5]
    beta_t2A_Y <- Y[6]
  }
  
  
  # Validate all required parameters are provided
  required_params <- c("beta_0_A", "beta_U1_A","beta_t_A", "beta_0_Y", "beta_t_Y",
                       "beta_t2_Y", "beta_A_Y", "beta_tA_Y", "beta_t2A_Y"
                       )
```


```{r}
set.seed(seed)
dt <- CJ(id = 1:nsim, time = 0:(K - 1))

indiv <- data.table(
  id = 1:nsim,
  U1 = runif(nsim, min = 0, max = 1)
)

indiv[, A0 := rbinom(nsim, 1, plogis(beta_0_A + beta_U1_A * U1))]

```

```{r}
# Step 2: Merge in individual-level covariates (U1, U2, A)
dt <- merge(dt, indiv, by = "id")
rm(indiv)

# Step 1: Expand to full panel (id x time)
dt[, `:=`(
  t2 = time^2,
  tstart = time,
  tstop = time + 1)  # Step 3: Add squared time and other derived variables
][, Astar := fifelse(A0 == 0 & time>0, rbinom(.N, 1, plogis(beta_t_A)), 0)][, trt_time := ifelse(A0 == 1, 0, which(Astar == 1)[1]), by = id 
] [,A := fifelse(A0 == 1, 1, fifelse(!is.na(trt_time) & time >= trt_time, 1, 0))][, Astar := NULL][, trt_time := NULL]
#here if there is patients that never started the treatment would return NA in all trt_time and mass up with rest of analysis
#so we replace all NA A to  0
dt = dt %>% 
  mutate(across(A, ~ replace_na(.x, 0)))
```

```{r,fig.height=5,fig.width=6}
dt %>% select(A, time)%>% group_by(time)%>% summarise(per_A = sum(A)/nsim) %>% 
  plot(main = "Percentage of Inititation by time ",
       ylab =" Percentage of Initiation (%)",
       xlab = "Time after eligible (Month)", ylim = c(0,1))
```
```{r}
# Step 2: Merge in individual-level covariates (U1, U2, A)
dt[, Ystar := rbinom(nsim*K, 1, plogis(
  beta_0_Y  +
    beta_t_Y * time + beta_t2_Y * t2 +
    beta_A_Y * A + beta_tA_Y * time * A +
    beta_t2A_Y * t2 * A))
][, event_time := which(Ystar == 1)[1], by = id # Step 6: Censor at first Ystar per individual
]
```
```{r,fig.height=5,fig.width=6}
dt %>%  
  filter(!is.na(event_time))%>% 
  select(id, event_time)%>%
  group_by(event_time)%>% summarise(n=n()/60)%>% mutate(per_Y = cumsum(n)/nsim)%>%
  ggplot(aes(x = event_time, y = per_Y))+ geom_point(shape = 1, size = 2) + theme_bw()+
  scale_y_continuous(
    limits = c(0, 1),
    labels = scales::number_format(accuracy = 0.1)
  ) +
  labs(x = "Time after eligible (Month)",
       y =" Percentage of cumulated outcome (%)",
       title = "Percentage of cumulative outcome by time")
```

```{r,fig.height=5,fig.width=6}
dt <- dt[time < event_time | is.na(event_time) == T][, event_time := NULL]
dt %>% select(A, time)%>% group_by(time)%>% summarise(per_A = sum(A)/nsim) %>% 
  plot(main = "Percentage of Inititation by time ",sub = "after cencoring inidivial after they experience heart failure",
       ylab =" Percentage of Initiation (%)",
       xlab = "Time after eligiavble (Month)", ylim = c(0,1))
```
```{r}

setnames(dt, old = c("time", "t2", "A", "Ystar"), new = c("cal_time", "cal_timesqr","trt", "outcome"))

#write.csv(dt,"Senario 1 simulated data 120226.csv ")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
